#%RAML 0.8

title: 众包平台
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:3000/api/
version: v1

traits:
  - secured:
      headers:
        X-Auth-Token:
          description: 当前用户token，用于验证权限,从登录返回的header中获取
          type: string
          required: true
          example: "IOC551fea47e4b02dd0ab568b85"

  - loginSecured:
      headers:
        X-Username:
          description: 用户名
          type: string
          required: true
        X-Password:
          description: 密码
          type: string
          required: true

/account:
  post:
    description: 用户注册
    body:
      application/json:
        schema: |
          {
            "name": "SB",
            "username": "XTDSB",
            "password": "123456",
            "email": "john@example.com"
          }
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "code": "200",
                "data": {
                  "id": 1,
                  "name": "SB",
                  "username": "XTDSB",
                  "state": "active",
                  "avatar_url": null,
                  "created_at": 1459246440000,
                  "is_admin": true,
                  "email": "john@example.com",
                  "private_token": "9koXpg98eAheJpvBs5tK"
                },
                "message": "操作成功",
                "success": true
              }
  /authentication:
    post:
      description: 用户登录获取token，通过headers返回
      is: [loginSecured]
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code": "200",
                  "data": {
                    "id": 1,
                    "name": "SB",
                    "username": "XTDSB",
                    "state": "active",
                    "avatar_url": null,
                    "created_at": 1459246440000,
                    "is_admin": true,
                    "email": "john@example.com",
                    "private_token": "9koXpg98eAheJpvBs5tK"
                  },
                  "message": "操作成功",
                  "success": true
                }

/project:
  /projects:
    get:
      is: [ secured ]
      description: 获取项目列表
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "code": "200",
                  "data":
                    [
                      {
                        "id": 1,
                        "name": "Dota",
                        "created_at": 1459246440000,
                        "member": [
                          {
                            "id": 1,
                            "name": "SB",
                            "username": "XTDSB",
                            "state": "active",
                            "avatar_url": null,
                            "created_at": 1459246440000,
                            "is_admin": true,
                            "email": "john@example.com",
                          },
                          {},
                          ...
                        ]
                      },
                      {},
                      ...
                    ],
                  "message": "操作成功",
                  "success": true
                }
  /{id}/members:
    get:
      is: [ secured ]
      description: 获取项目成员
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "code": "200",
                  "data":
                    [
                      {
                        "id": 1,
                        "name": "SB",
                        "username": "XTDSB",
                        "state": "active",
                        "avatar_url": null,
                        "created_at": 1459246440000,
                        "is_admin": true,
                        "email": "john@example.com",
                      },
                      {},
                      ...
                    ],
                  "message": "操作成功",
                  "success": true
                }
  /{id}/issues:
    get:
      is: [ secured ]
      description: 获取项目问题列表
      queryParameters:
        pageSize:
          description: "页面大小，可选，默认为10"
          type: number
        pageNum:
          description: "页数，可选，默认为1"
          type: number
        order:
          description: "排序方式"
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "code": "200",
                  "data":
                    [
                      {
                        "state" : "opened",
                        "description" : "Ratione dolores corrupti mollitia soluta quia.",
                        "author" : {
                           "state" : "active",
                           "id" : 18,
                           "web_url" : "https://gitlab.example.com/u/eileen.lowe",
                           "name" : "Alexandra Bashirian",
                           "avatar_url" : null,
                           "username" : "eileen.lowe"
                        },
                        "milestone" : {
                           "project_id" : 1,
                           "description" : "Ducimus nam enim ex consequatur cumque ratione.",
                           "state" : "closed",
                           "due_date" : null,
                           "iid" : 2,
                           "created_at" : "2016-01-04T15:31:39.996Z",
                           "title" : "v4.0",
                           "id" : 17,
                           "updated_at" : "2016-01-04T15:31:39.996Z"
                        },
                        "project_id" : 1,
                        "assignee" : {
                           "state" : "active",
                           "id" : 1,
                           "name" : "Administrator",
                           "web_url" : "https://gitlab.example.com/u/root",
                           "avatar_url" : null,
                           "username" : "root"
                        },
                        "updated_at" : "2016-01-04T15:31:51.081Z",
                        "id" : 76,
                        "title" : "Consequatur vero maxime deserunt laboriosam est voluptas dolorem.",
                        "created_at" : "2016-01-04T15:31:51.081Z",
                        "iid" : 6,
                        "labels" : [],
                        "subscribed" : false,
                        "user_notes_count": 1,
                        "due_date": "2016-07-22"
                      },
                      {},
                      ...
                    ],
                  "paginator": {
                     "page":1,
                     "items": 10,
                     "itemsPerPage":10,
                     "totalItems":43,
                     "totalPages": 5
                    },
                  "message": "操作成功",
                  "success": true
                }
